const firebaseErrors = {
  "app-deleted": "데이터베이스가 발견되지 않았다.",
  "expired-action-code": "행동 코드나 링크가 만료되었습니다.",
  "invalid-action-code": "행동강령은 유효하지 않습니다. 코드가 잘못 형성되었거나 이미 사용된 경우일 수 있습니다.",
  "user-disabled": "제공된 자격증에 해당하는 사용자가 비활성화되었습니다.",
  "user-not-found": "사용자는 어떤 자격증과도 일치하지 않습니다.",
  "weak-password": "비밀번호가 너무 약해서",
  "email-already-in-use": "나는 이미 제공된 이메일 주소가 있는 계정을 가지고 있었다.",
  "invalid-email": "이메일 주소가 유효하지 않습니다.",
  "operation-not-allowed": "이 인증서에 해당하는 계정 유형은 아직 활성화되지 않았습니다.",
  "account-exists-with-different-credential": "이미 다른 계정과 연결된 이메일",
  "auth-domain-config-required": "인증할 수 있는 설정이 제공되지 않았습니다.",
  "credential-already-in-use": "이 자격 증명에 대한 계정이 이미 있습니다.",
  "operation-not-supported-in-this-environment":
      "이 작업은 실행 중인 환경에서는 지원되지 않습니다. 반드시 http 또는 https.",
  "timeout": "응답시간이 초과되었습니다. 도메인이 운영을 할 수 있는 권한이 없을 수도 있습니다.",
  "missing-android-pkg-name": "안드로이드 앱을 설치하기 위해서는 패키지 이름이 제공되어야 한다.",
  "missing-continue-uri": "다음 URL은 요청 시 제공되어야 합니다.",
  "missing-ios-bundle-id": "iOS 앱을 설치하기 위해서는 패키지 이름이 제공되어야 한다.",
  "invalid-continue-uri": "요청서에 제공된 다음 URL은 유효하지 않습니다.",
  "unauthorized-continue-uri": "다음 URL의 도메인은 화이트리스트에 없습니다.",
  "invalid-dynamic-link-domain":
      "현재 프로젝트에서 제공하는 동적 링크 도메인은 승인되지 않았거나 설정되지 않았습니다.",
  "argument-error": "애플리케이션을 위한 링크 설정을 확인해 보세요.",
  "invalid-persistence-type": "데이터 지속성을 위해 지정된 유형은 유효하지 않습니다.",
  "unsupported-persistence-type": "현재 환경은 데이터 지속성에 대해 지정된 유형을 지원하지 않습니다.",
  "invalid-credential": "신분증 유효기간이 지났거나 기형상태입니다.",
  "wrong-password": "비밀번호가 틀렸습니다.",
  "invalid-verification-code": "인증서 인증 코드는 유효하지 않습니다.",
  "invalid-verification-id": "인증 ID는 유효하지 않습니다.",
  "custom-token-mismatch": "토큰은 요청한 표준과 다릅니다.",
  "invalid-custom-token": "제공된 토큰은 유효하지 않습니다.",
  "captcha-check-failed": "리캡차 응답 토큰은 유효하지 않거나 만료되었거나 도메인이 허용되지 않습니다.",
  "invalid-phone-number": "전화번호는 유효하지 않은 형식(E.164 표준)입니다.",
  "missing-phone-number": "전화번호는 필수입니다.",
  "quota-exceeded": "SMS 수수료가 초과되었습니다.",
  "cancelled-popup-request": "한 번에 하나의 팝업창 요청만 허용됩니다.",
  "popup-blocked": "내비게이터가 팝업창을 막았습니다.",
  "popup-closed-by-user": "사용자는 공급업체에서 로그인하지 않은 상태에서 팝업 창을 닫았습니다.",
  "unauthorized-domain": "애플리케이션 도메인은 운영을 할 수 있는 권한이 없습니다.",
  "invalid-user-token": "현재 사용자는 확인되지 않았습니다.",
  "user-token-expired": "현재 사용자의 토큰이 만료되었습니다.",
  "null-user": "현재 사용자는 0입니다.",
  "app-not-authorized": "주어진 키로 자신을 인증할 수 있는 권한이 없는 앱",
  "invalid-api-key": "제공된 API 키는 유효하지 않습니다.",
  "network-request-failed": "네트워크에 접속할 때의 오류라고 했습니다.",
  "requires-recent-login": "마지막 사용자 접근 시간은 보안 제한에 부합하지 않습니다.",
  "too-many-requests": "예상치 않은 활동으로 인해 신청이 차단되었습니다. 잠시 후 다시 시도해주세요",
  "web-storage-unsupported": "내비게이터는 저장장치와 호환되지 않거나 사용자가 이 기능을 비활성화한 경우",
  "invalid-claims": "개인화된 등록 속성은 유효하지 않습니다.",
  "claims-too-large": "신청서 크기가 최대 허용 크기인 1메가바이트를 초과합니다.",
  "id-token-expired": "정보화된 토큰이 만료되었습니다.",
  "id-token-revoked": "정보화된 토큰이 만료되었습니다.",
  "invalid-argument": "한 가지 방법에 대해 유효하지 않은 주장이 제시되었습니다.",
  "invalid-creation-time": "창작 시간은 유효한 UTC 날짜여야 합니다.",
  "invalid-disabled-field": "장애인을 위한 소유권은 유효하지 않습니다.",
  "invalid-display-name": "아이디는 유효하지 않습니다.",
  "invalid-email-verified": "이메일은 유효하지 않습니다.",
  "invalid-hash-algorithm": "HASH 알고리즘은 암호와 호환되지 않습니다.",
  "invalid-hash-block-size": "HASH 블록의 크기는 유효하지 않습니다.",
  "invalid-hash-derived-key-length": "HASH에서 파생된 키의 크기는 유효하지 않습니다.",
  "invalid-hash-key": "HASH 키에는 유효한 바이트 버퍼가 있어야 합니다.",
  "invalid-hash-memory-cost": "HASH 메모리 비용은 유효하지 않습니다.",
  "invalid-hash-parallelization": "HASH 병렬 전하량은 유효하지 않습니다.",
  "invalid-hash-rounds": "HASH 반올림은 유효하지 않습니다.",
  "invalid-hash-salt-separator": "HASH 생성 알고리즘의 SALT 분리 필드는 유효한 바이트 버퍼여야 합니다.",
  "invalid-id-token": "입력된 토큰 코드는 유효하지 않습니다.",
  "invalid-last-sign-in-time": "마지막 로그인 시간은 유효한 UTC 날짜여야 합니다.",
  "invalid-page-token": "요청서에 제공된 다음 URL은 유효하지 않습니다.",
  "invalid-password": "비밀번호는 유효하지 않습니다. 최소 6자 길이의 비밀번호가 있어야 합니다.",
  "invalid-password-hash": "HASH 비밀번호는 유효하지 않습니다.",
  "invalid-password-salt": "SALT 비밀번호는 유효하지 않습니다.",
  "invalid-photo-url": "사용자 사진 URL은 유효하지 않습니다.",
  "invalid-provider-id": "공급자 식별자는 지원되지 않습니다.",
  "invalid-session-cookie-duration":
      "쿠키 세션의 기간은 1밀리초, 5분에서 2주 사이에 유효한 숫자여야 합니다.",
  "invalid-uid": "제공된 식별자는 최대 128자여야 합니다.",
  "invalid-user-import": "수입할 사용자 등록은 유효하지 않습니다.",
  "invalid-provider-data": "데이터 제공자는 유효하지 않습니다.",
  "maximum-user-count-exceeded": "최대한 많은 사용자가 수입할 수 있도록 허용되었습니다.",
  "missing-hash-algorithm": "사용자를 수입하기 위해서는 HASH 생성 알고리즘과 그 매개 변수를 제공해야 합니다.",
  "missing-uid": "현재 운용을 위해서는 식별자가 필요합니다.",
  "reserved-claims": "하나 이상의 맞춤화된 속성이 사용된 예약 단어를 제공했습니다.",
  "session-cookie-revoked": "쿠키 세션이 만료되었습니다.",
  "uid-alread-exists": "제공된 식별자는 이미 사용 중입니다.",
  "email-already-exists": "제공된 이메일은 이미 사용 중입니다.",
  "phone-number-already-exists": "제공된 전화는 이미 사용 중입니다.",
  "project-not-found": "프로젝트는 발견되지 않았다.",
  "insufficient-permission": "사용된 자격증은 요청된 자원에 접근할 수 없습니다.",
  "internal-error": "인증 서버가 요청을 처리하려고 시도하다가 예기치 않은 오류를 발견했습니다."
};
