// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsEw1PTkhPbAIQEt1t9TIVFiiP0J5B5U',
    appId: '1:379512078837:web:486460e8ca67b71024a0bc',
    messagingSenderId: '379512078837',
    projectId: 'tiktok-clone-vgandam',
    authDomain: 'tiktok-clone-vgandam.firebaseapp.com',
    storageBucket: 'tiktok-clone-vgandam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUkN-NCasDes7r-IJW-edP75ZGGuCaTA',
    appId: '1:379512078837:android:6470f843058ba53d24a0bc',
    messagingSenderId: '379512078837',
    projectId: 'tiktok-clone-vgandam',
    storageBucket: 'tiktok-clone-vgandam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWHG28IKsRWxrrz38LhAAjGvePTEA_G4g',
    appId: '1:379512078837:ios:ad76d63864c541a924a0bc',
    messagingSenderId: '379512078837',
    projectId: 'tiktok-clone-vgandam',
    storageBucket: 'tiktok-clone-vgandam.appspot.com',
    iosClientId: '379512078837-ijo0qq47luavvt3a54vau1nrpm0ieagq.apps.googleusercontent.com',
    iosBundleId: 'com.halfbaek.tiktokClone',
  );
}
